### ISSUE TITLE
Question Regarding License for This Project

### ISSUE THREAD

**Issue by yixian929** [uw-cmg/MoleProp#1]
Hello,

I am interested in using your project, but I noticed that there is no license specified in the repository. Could you please clarify under which license this project is released? Adding a license file (e.g., MIT, GPL, etc.) would help other developers understand how they can use and contribute to your project.

Thank you for your time, and I look forward to your response!

Best regards,

**Comment by ddmorgan** [comment]
Thanks for noticing this issue.  I have added the MIT license.

**Comment by yixian929** [comment]
Hello ddmorgan,

Thank you for your prompt response and for adding the MIT license. I appreciate it!

Best regards,
